app:
  name: EngageIQ
  version: 1.0.1
  environment: production
  debug: false

api:
  host: 0.0.0.0
  port: 8000
  cors_origins:
    - https://your-app-name.onrender.com

data:
  sources:
    agent_persona: "Agent_persona.csv"
    campaigns: "campaigns.csv"
  connector: postgres

connectors:
  csv:
    type: local_file
    location: "./data"
    delimiter: ","
    encoding: "utf-8"
    skip_rows: 0
    cache_enabled: true
    cache_ttl: 3600

  postgres:
    type: database
    provider: postgresql
    # Use DATABASE_URL for Neon (recommended)
    url: ${DATABASE_URL}
    # Alternative: individual components
    # host: ${POSTGRES_HOST}
    # port: ${POSTGRES_PORT}
    # database: ${POSTGRES_DB}
    # user: ${POSTGRES_USER}
    # password: ${POSTGRES_PASSWORD}
    pool_size: 10
    max_overflow: 20
    pool_pre_ping: true
    pool_recycle: 300

llm:
  default_provider: claude
  providers:
    claude:
      api_key: ${ANTHROPIC_API_KEY}
      model: claude-sonnet-4-20250514
      max_tokens: 4000
      temperature: 0.7
    openai:
      api_key: ${OPENAI_API_KEY}
      model: gpt-4
      max_tokens: 4000

agents:
  orchestrator:
    enabled: true
    timeout: 300
    max_retries: 3
  goal_parser:
    enabled: true
    provider: claude
    temperature: 0.5
  data_loader:
    enabled: true
    cache_enabled: true
    include_additional: true
  segmentation:
    enabled: true
    default_method: rule_based
  profiler:
    enabled: true
    calculate_lift: true
  campaign_strategist:
    enabled: true
    provider: claude
    temperature: 0.8
